version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sto_system_app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - sto_network

  db:
    image: mysql:8.0
    container_name: sto_system_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - sto_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sto_system_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ""
    depends_on:
      - db
    networks:
      - sto_network

networks:
  sto_network:
    driver: bridge

volumes:
  dbdata:
    driver: local
